const routes = {
    //Admin
    admin: '/admin',
    dashboard: '/admin/dashboard',
    navigationList: '/admin/navigation-list',
    addNavigation: '/admin/add-navigation',
    editNavigation: '/admin/edit-navigation/:id',
    productList: '/admin/product-list',
    addProduct: '/admin/add-product',
    editProduct: '/admin/edit-product/:id',
    newsList: '/admin/news-list',
    addNews: '/admin/add-news',
    updateNews: '/admin/update-news/:id',
    // recruitmentList: '/admin/recruitment-list',
    // addRecruitment: '/admin/add-recruitment',
    // updateRecruitment: '/admin/update-recruitment/:id',
    serviceList: '/admin/service-list',
    addService: '/admin/add-service',
    updateService: '/admin/update-service/:id',
    experienceList: '/admin/experience-list',
    addExperience: '/admin/add-experience',
    updateExperience: '/admin/update-experience/:id',
    partnerList: '/admin/partner-list',
    addPartner: '/admin/add-partner',
    updateUser: '/admin/update-user/:id',
    changePassword: '/admin/change-password',
    userList: '/admin/user-list',
    addUser: '/admin/add-user',
    videosList: '/admin/videos-list',
    imagesList: '/admin/images-list',
    addImage: '/admin/add-image',
    addVideo: '/admin/add-video',
    messagesList: '/admin/messages-list',
    settings: '/admin/settings',
    pageList: '/admin/page-list',
    addPage: '/admin/add-page',
    updatePage: '/admin/update-page',
    categoryList: '/admin/category-list',
    addCategory: '/admin/add-category',
    updateCategory: '/admin/update-category/:id',
    memberList: '/admin/member-list',
    addMember: '/admin/add-member',
    updateMember: '/admin/update-member/:id',
    orderList: '/admin/order-list',
    //User
    home: '/',
    // about: '/gioi-thieu',
    introduction: '/gioi-thieu/:slug',
    products: '/san-pham',
    productCategory: '/san-pham/:slug',
    productDetail: '/san-pham/:category/:id',
    news: '/bai-viet',
    newsDetail: `/bai-viet/:slug/:id`,
    newsCategory: `/bai-viet/:slug`,
    search: '/search',
    projects: '/du-an',
    projectCategory: '/du-an/:slug',
    projectDetail: '/du-an/:category/:id',
    // services: '/dich-vu',
    // serviceDetail: '/dich-vu/:category/:id',
    // servicesCategory: `/dich-vu/:slug`,
    // experiences: '/trai-nghiem',
    // experienceDetail: '/trai-nghiem/:category/:id',
    // experiencesCategory: `/trai-nghiem/:slug`,
    // recruitment: '/tuyen-dung',
    // recruitmentDetail: `/tuyen-dung/:category/:id`,
    // recruitmentCategory: '/tuyen-dung/:slug',
    error404: '/404',
    contact: '/lien-he',
    privacy: '/dieu-khoan-chinh-sach',
    cart: '/gio-hang',
    checkout: '/thanh-toan',
    orderReceived: '/thanh-toan/order-received/:id',
    // buyingGuide: '/huong-dan-mua-hang',
    policyCom: '/:slug',
    // policy: '/chinh-sach/:slug',
    // customerLogin: '/dang-nhap',
};

export default routes;
